name = "omniattend-core"
main = "worker.ts"
compatibility_date = "2025-01-01"

workers_dev = true
compatibility_flags = ["nodejs_compat"]

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "omniattend-db"
database_id = "你的 D1 database_id"

# 前端静态资源绑定（关键）
[assets]
directory = "./dist"
binding = "ASSETS"
